<?php

use yii\db\Migration;

/**
 * Class m200823_154810_revert_widgets
 */
class m200823_154810_revert_widgets extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute(<<<SQL
            DELETE FROM `theme_widgets`;
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (1, '1-row header with logo, nav and popup cart', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\OneRowHeaderWithCart\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\OneRowHeaderWithCart\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/OneRowHeaderWithCart/views/_config.php', '{}', 1, 86400, NULL, 1);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (2, '1-row header with logo, nav', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\OneRowHeader\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\OneRowHeader\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/OneRowHeader/views/_config.php', '{}', 1, 86400, NULL, 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (3, 'Slider', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Slider\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Slider\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/Slider/views/_config.php', '{}', 1, 86400, NULL, 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (4, 'Categories list', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\CategoriesList\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\CategoriesList\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/CategoriesList/views/_config.php', '{}', 0, 0, 'app\\\\modules\\\\shop\\\\models\\\\Category', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (5, 'Filter widget', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\FilterSets\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\FilterSets\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/FilterSets/views/_config.php', '{}', 0, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (6, 'Pages list', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\PagesList\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\PagesList\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/PagesList/views/_config.php', '{}', 1, 86400, 'app\\\\modules\\\\page\\\\models\\\\Page', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (7, 'Content block', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\ContentBlock\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\ContentBlock\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/ContentBlock/views/_config.php', '{}', 1, 86400, 'app\\\\modules\\\\page\\\\models\\\\Page', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (8, 'Footer', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Footer\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Footer\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/Footer/views/_config.php', '{}', 1, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (9, 'Navigation', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Navigation\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\Navigation\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/Navigation/views/_config.php', '{}', 1, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (10, 'Last Viewed Products', 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\LastViewedProducts\\\\Widget', NULL, 'app\\\\extensions\\\\DefaultTheme\\\\widgets\\\\LastViewedProducts\\\\ConfigurationModel', '@app/extensions/DefaultTheme/widgets/LastViewedProducts/views/_config.php', '{}', 0, 0, '', 0);
SQL
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->execute(<<<SQL
            DELETE FROM `theme_widgets`;
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (1, '1-row header with logo, nav and popup cart', 'app\\\\\web\\\\theme\\\\widgets\\\\OneRowHeaderWithCart\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\OneRowHeaderWithCart\\\\ConfigurationModel', '@app/web/theme/widgets/OneRowHeaderWithCart/views/_config.php', '{}', 1, 86400, NULL, 1);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (2, '1-row header with logo, nav', 'app\\\\web\\\\theme\\\\widgets\\\\OneRowHeader\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\OneRowHeader\\\\ConfigurationModel', '@app/web/theme/widgets/OneRowHeader/views/_config.php', '{}', 1, 86400, NULL, 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (3, 'Slider', 'app\\\\web\\\\theme\\\\widgets\\\\Slider\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\Slider\\\\ConfigurationModel', '@app/web/theme/widgets/Slider/views/_config.php', '{}', 1, 86400, NULL, 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (4, 'Categories list', 'app\\\\web\\\\theme\\\\widgets\\\\CategoriesList\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\CategoriesList\\\\ConfigurationModel', '@app/web/theme/widgets/CategoriesList/views/_config.php', '{}', 0, 0, 'app\\\\modules\\\\shop\\\\models\\\\Category', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (5, 'Filter widget', 'app\\\\web\\\\theme\\\\widgets\\\\FilterSets\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\FilterSets\\\\ConfigurationModel', '@app/web/theme/widgets/FilterSets/views/_config.php', '{}', 0, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (6, 'Pages list', 'app\\\\web\\\\theme\\\\widgets\\\\PagesList\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\PagesList\\\\ConfigurationModel', '@app/web/theme/widgets/PagesList/views/_config.php', '{}', 1, 86400, 'app\\\\modules\\\\page\\\\models\\\\Page', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (7, 'Content block', 'app\\\\web\\\\theme\\\\widgets\\\\ContentBlock\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\ContentBlock\\\\ConfigurationModel', '@app/web/theme/widgets/ContentBlock/views/_config.php', '{}', 1, 86400, 'app\\\\modules\\\\page\\\\models\\\\Page', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (8, 'Footer', 'app\\\\web\\\\theme\\\\widgets\\\\Footer\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\Footer\\\\ConfigurationModel', '@app/web/theme/widgets/Footer/views/_config.php', '{}', 1, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (9, 'Navigation', 'app\\\\web\\\\theme\\\\widgets\\\\Navigation\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\Navigation\\\\ConfigurationModel', '@app/web/theme/widgets/Navigation/views/_config.php', '{}', 1, 0, '', 0);
            INSERT INTO `theme_widgets` (`id`, `name`, `widget`, `preview_image`, `configuration_model`, `configuration_view`, `configuration_json`, `is_cacheable`, `cache_lifetime`, `cache_tags`, `cache_vary_by_session`) VALUES (10, 'Last Viewed Products', 'app\\\\web\\\\theme\\\\widgets\\\\LastViewedProducts\\\\Widget', NULL, 'app\\\\web\\\\theme\\\\widgets\\\\LastViewedProducts\\\\ConfigurationModel', '@app/web/theme/widgets/LastViewedProducts/views/_config.php', '{}', 0, 0, '', 0);
SQL
        );
    }
}
