{{- if (eq .Values.global.env "dev")}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ .Chart.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - mag-dev.dev59.ru
    secretName: magdev-tls-secret
  rules:
  - host: mag-dev.dev59.ru
    http:
      paths:
      - path: /
        backend:
          serviceName:  {{ .Chart.Name }}-service
          servicePort: http
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-wildcard
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - host: sextoys365.ru
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-service
          servicePort: http
        path: /
  - host: '*.sextoys365.ru'
    http:
      paths:
      - backend:
          serviceName: magazin-service
          servicePort: http
        path: /
  tls:
  - hosts:
    - sextoys365.ru
    - '*.sextoys365.ru'
    secretName: magdev-wildcard
{{- end }}
