---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-mysql-migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "werf.io/skip-logs": "false"
spec:
  activeDeadlineSeconds: 2400
  template:
    metadata:
      name: mysql-migration
    spec:
      volumes:
      - name: dbcred-config
        configMap:
          name: {{ .Chart.Name }}-dbcred-configmap
      restartPolicy: OnFailure
      initContainers:
      - name: wait-mysql
        image: alpine:3
        command: ['/bin/sh', '-c', 'while ! getent ahostsv4 mysql.database.svc.cluster.local; do sleep 1;done']
      containers:
      - name: yii-migrate
        command: [ 'bash', '-c', '-l', 'php yii migrate --interactive=0' ]
{{ tuple "app" . | include "werf_container_image" | indent 8 }}
        volumeMounts:
        - name: dbcred-config
          mountPath: /app/config/db-local.php
          subPath: db-local.php